### ISSUE TITLE
new energy solution in HA 2021.8

### ISSUE THREAD

**Issue by FlingersDH7** [thomascys/solaxcloud#9]
The new energy solution in Ha 2021.8 can include solarpanels.
But the sensors of the panels needs some properties to be able to be picked up.

See: https://developers.home-assistant.io/docs/core/entity/sensor/#properties

**Comment by riddertommie** [comment]
I'm struggling on that, any tips?

**Comment by pieterzen** [comment]
I switched to the REST implementation and that works out of the box:
```
#########################################################
#                                                       #
#         SOLAX CLOUD.                                  #
#                                                       #
#########################################################
- platform: rest
  resource: https://www.eu.solaxcloud.com:9443/proxy/api/getRealtimeInfo.do?tokenId=xxxxxxxxxxxxxxxxxxx&sn=xxxxxx`
  name: "Solax"
  json_attributes_path: "$.result"
  json_attributes:
    - yieldtoday
    - yieldtotal
    - acpower
    - uploadTime
    - inverterStatus
  value_template: "1" # dummy value, not used; avoids the "State max length is 255 characters" error
- platform: template
  sensors:
    solax_yield_today:
      friendly_name: "Solax yield today"
      value_template: "{{ state_attr('sensor.solax', 'yieldtoday') }}"
      unit_of_measurement: "KWh"
      device_class: energy
    solax_yield_total:
      friendly_name: "Solax yield total"
      value_template: "{{ state_attr('sensor.solax', 'yieldtotal') }}"
      unit_of_measurement: "KWh"
      device_class: energy
    solax_power_now:
      friendly_name: "Solax power now"
      value_template: "{{ state_attr('sensor.solax', 'acpower') }}"
      unit_of_measurement: "W"
      device_class: power
    solax_yield_delta:
      friendly_name: "Solax yield delta"
      value_template: "{{ state_attr('sensor.solax', 'acpower') /12000 }}"
      unit_of_measurement: "kWh"
      device_class: energy
    solax_upload_time:
      friendly_name: "Solax update time"
      value_template: "{{ state_attr('sensor.solax', 'uploadTime') }}"
    solax_status:
      friendly_name: "Solax status"
      value_template: >
        {% if state_attr('sensor.solax', 'inverterStatus') == '100' %}Wait
        {% elif state_attr('sensor.solax', 'inverterStatus') == '101' %}Check
        {% elif state_attr('sensor.solax', 'inverterStatus') == '102' %}Normal
        {% elif state_attr('sensor.solax', 'inverterStatus') == '103' %}Fault
        {% elif state_attr('sensor.solax', 'inverterStatus') == '104' %}Permanent Fault
        {% elif state_attr('sensor.solax', 'inverterStatus') == '105' %}Update
        {% elif state_attr('sensor.solax', 'inverterStatus') == '106' %}EPS Check
        {% elif state_attr('sensor.solax', 'inverterStatus') == '107' %}EPS
        {% elif state_attr('sensor.solax', 'inverterStatus') == '108' %}Self-test
        {% elif state_attr('sensor.solax', 'inverterStatus') == '109' %}Idle
        {% elif state_attr('sensor.solax', 'inverterStatus') == '110' %}Standby
        {% elif state_attr('sensor.solax', 'inverterStatus') == '111' %}Pv Wake Up Bat
        {% elif state_attr('sensor.solax', 'inverterStatus') == '112' %}Gen Check
        {% elif state_attr('sensor.solax', 'inverterStatus') == '113' %}Gen Run
        {% else %}I dont know{% endif %}
```
- I'm not sure where I got this script from; Sorry developer if you read this.
